#ifndef GHOST_NETWORK_ERRORS_H
#define GHOST_NETWORK_ERRORS_H

// Network error codes
typedef enum {
    // Success
    NET_ERR_SUCCESS = 0,

    // General errors
    NET_ERR_FAILED = -1,
    NET_ERR_INVALID_PARAM = -2,
    NET_ERR_NOT_INITIALIZED = -3,
    NET_ERR_ALREADY_INITIALIZED = -4,
    NET_ERR_OUT_OF_MEMORY = -5,
    NET_ERR_BUFFER_FULL = -6,
    NET_ERR_BUFFER_EMPTY = -7,
    NET_ERR_NOT_FOUND = -8,
    NET_ERR_ALREADY_EXISTS = -9,
    NET_ERR_NOT_SUPPORTED = -10,
    NET_ERR_WOULD_BLOCK = -11,
    NET_ERR_TIMEOUT = -12,

    // Interface errors
    NET_ERR_INTERFACE_DOWN = -20,
    NET_ERR_INTERFACE_NOT_FOUND = -21,
    NET_ERR_INTERFACE_ALREADY_EXISTS = -22,
    NET_ERR_INTERFACE_FULL = -23,
    NET_ERR_INTERFACE_ERROR = -24,

    // Connection errors
    NET_ERR_CONNECTION_FAILED = -30,
    NET_ERR_CONNECTION_CLOSED = -31,
    NET_ERR_CONNECTION_RESET = -32,
    NET_ERR_CONNECTION_ABORTED = -33,
    NET_ERR_CONNECTION_REFUSED = -34,
    NET_ERR_CONNECTION_TIMEOUT = -35,
    NET_ERR_CONNECTION_IN_PROGRESS = -36,

    // Packet errors
    NET_ERR_PACKET_TOO_LARGE = -40,
    NET_ERR_PACKET_TOO_SMALL = -41,
    NET_ERR_PACKET_INVALID = -42,
    NET_ERR_PACKET_CHECKSUM = -43,
    NET_ERR_PACKET_VERSION = -44,
    NET_ERR_PACKET_PROTOCOL = -45,

    // Security errors
    NET_ERR_SECURITY_VIOLATION = -50,
    NET_ERR_AUTHENTICATION_FAILED = -51,
    NET_ERR_ENCRYPTION_FAILED = -52,
    NET_ERR_DECRYPTION_FAILED = -53,
    NET_ERR_INTEGRITY_CHECK_FAILED = -54,
    NET_ERR_ACCESS_DENIED = -55,
    NET_ERR_CERTIFICATE_INVALID = -56,
    NET_ERR_SIGNATURE_INVALID = -57,

    // Protocol errors
    NET_ERR_PROTOCOL_ERROR = -60,
    NET_ERR_PROTOCOL_VERSION = -61,
    NET_ERR_PROTOCOL_NOT_SUPPORTED = -62,
    NET_ERR_PROTOCOL_INVALID_STATE = -63,
    NET_ERR_PROTOCOL_INVALID_COMMAND = -64,
    NET_ERR_PROTOCOL_INVALID_RESPONSE = -65,

    // Resource errors
    NET_ERR_NO_RESOURCES = -70,
    NET_ERR_RESOURCE_BUSY = -71,
    NET_ERR_RESOURCE_QUOTA_EXCEEDED = -72,
    NET_ERR_RESOURCE_TEMPORARILY_UNAVAILABLE = -73,
    NET_ERR_RESOURCE_DEADLOCK = -74,

    // System errors
    NET_ERR_SYSTEM_ERROR = -80,
    NET_ERR_NOT_IMPLEMENTED = -81,
    NET_ERR_NOT_READY = -82
} NetworkError;

#endif // GHOST_NETWORK_ERRORS_H
