#ifndef GHOST_SYSTEM_CONFIG_H
#define GHOST_SYSTEM_CONFIG_H

// System-wide Constants
#define GHOST_MAX_PROCESSES 256
#define GHOST_MAX_THREADS_PER_PROCESS 64
#define GHOST_MAX_NETWORK_INTERFACES 8
#define GHOST_MAX_NETWORK_CONNECTIONS 1024
#define GHOST_MAX_OPEN_FILES 1024
#define GHOST_MAX_FILE_DESCRIPTORS 4096

// Memory Configuration
#define GHOST_PAGE_SIZE 4096
#define GHOST_KERNEL_HEAP_SIZE (16 * 1024 * 1024)  // 16MB
#define GHOST_USER_STACK_SIZE (1 * 1024 * 1024)    // 1MB
#define GHOST_KERNEL_STACK_SIZE (64 * 1024)        // 64KB

// Network Configuration
#define GHOST_MAX_PACKET_SIZE 65536
#define GHOST_CONNECTION_TIMEOUT 30000  // 30 seconds
#define GHOST_MAX_BACKLOG 128

// Security Configuration
#define GHOST_MAX_SECURITY_EVENTS 1024
#define GHOST_MAX_SECURITY_MONITORS 16
#define GHOST_SECURITY_LOG_SIZE (1 * 1024 * 1024)  // 1MB

// Process Configuration
#define GHOST_PROCESS_NAME_MAX 256
#define GHOST_MAX_PROCESS_ARGS 128
#define GHOST_MAX_ENV_VARS 256

// Filesystem Configuration
#define GHOST_PATH_MAX 4096
#define GHOST_NAME_MAX 255
#define GHOST_MAX_SYMLINK_DEPTH 8

// System Timing
#define GHOST_TIMER_FREQUENCY 1000  // 1kHz
#define GHOST_SCHEDULER_QUANTUM 10  // 10ms

#endif // GHOST_SYSTEM_CONFIG_H
